<?php

/**
 * @file
 * dt_core_info.variable.inc
 */

/**
 * Implements hook_variable_realm_default_variables().
 */
function dt_core_info_variable_realm_default_variables() {
  $realm_variables = array();
  $realm_variables['language']['bg'] = array(
    'site_name' => 'Европейска комисия',
    'site_slogan' => 'Политики, информация и услуги',
  );
  $realm_variables['language']['cs'] = array(
    'site_name' => 'Evropská komise',
    'site_slogan' => 'Oblasti politiky, informace a služby',
  );
  $realm_variables['language']['da'] = array(
    'site_name' => 'Europa-Kommissionen',
    'site_slogan' => 'Politikker, oplysninger og tjenester',
  );
  $realm_variables['language']['de'] = array(
    'site_name' => 'EU-Kommission',
    'site_slogan' => 'Politikfelder, Informationen und Dienste',
  );
  $realm_variables['language']['el'] = array(
    'site_name' => 'Ευρωπαϊκή Επιτροπή',
    'site_slogan' => 'Πολιτικές, πληροφορίες και υπηρεσίες',
  );
  $realm_variables['language']['en'] = array(
    'site_name' => 'European Commission',
    'site_slogan' => 'Policies, information and services',
  );
  $realm_variables['language']['es'] = array(
    'site_name' => 'Comisión Europea',
    'site_slogan' => 'Políticas, información y servicios',
  );
  $realm_variables['language']['et'] = array(
    'site_name' => 'Euroopa Komisjon',
    'site_slogan' => 'Poliitikavaldkonnad, teave ja teenused',
  );
  $realm_variables['language']['fi'] = array(
    'site_name' => 'Euroopan komissio',
    'site_slogan' => 'Politiikan alat, palvelut, tietolähteet',
  );
  $realm_variables['language']['fr'] = array(
    'site_name' => 'Commission européenne',
    'site_slogan' => 'Politiques, informations et services',
  );
  $realm_variables['language']['ga'] = array(
    'site_name' => 'An Coimisiún Eorpach',
    'site_slogan' => 'Beartais, eolas agus seirbhísí',
  );
  $realm_variables['language']['hr'] = array(
    'site_name' => 'Europska komisija',
    'site_slogan' => 'Politike, informacije i službe',
  );
  $realm_variables['language']['hu'] = array(
    'site_name' => 'Európai Bizottság',
    'site_slogan' => 'Szakpolitikák, információk és szolgálatok',
  );
  $realm_variables['language']['it'] = array(
    'site_name' => 'Commissione europea',
    'site_slogan' => 'Politiche, informazioni e servizi',
  );
  $realm_variables['language']['lt'] = array(
    'site_name' => 'Europos Komisija',
    'site_slogan' => 'Politika, informacija ir paslaugos',
  );
  $realm_variables['language']['lv'] = array(
    'site_name' => 'Eiropas Komisija',
    'site_slogan' => 'Politikas jomas, informācija un dienesti',
  );
  $realm_variables['language']['mt'] = array(
    'site_name' => 'Kummissjoni Ewropea',
    'site_slogan' => 'Politiki, informazzjoni u servizzi',
  );
  $realm_variables['language']['nl'] = array(
    'site_name' => 'Europese Commissie',
    'site_slogan' => 'Beleid, informatie en diensten',
  );
  $realm_variables['language']['pl'] = array(
    'site_name' => 'Komisja Europejska',
    'site_slogan' => 'Obszary polityki, informacje i usługi',
  );
  $realm_variables['language']['pt-pt'] = array(
    'site_name' => 'Comissão Europeia',
    'site_slogan' => 'Políticas, informações e serviços',
  );
  $realm_variables['language']['ro'] = array(
    'site_name' => 'Comisia Europeană',
    'site_slogan' => 'Politici, informații și servicii',
  );
  $realm_variables['language']['sk'] = array(
    'site_name' => 'Európska komisia',
    'site_slogan' => 'Politiky, informácie a služby',
  );
  $realm_variables['language']['sl'] = array(
    'site_name' => 'Evropska komisija',
    'site_slogan' => 'Politike, informacije in službe',
  );
  $realm_variables['language']['sv'] = array(
    'site_name' => 'Europeiska kommissionen',
    'site_slogan' => 'Politikområden, information och tjänster',
  );

  return $realm_variables;
}
